### ISSUE TITLE
Override back key 

### ISSUE THREAD

**Issue by sam16222** [Samsung/GearVRf#1038]
The application always redirects to an oculus environment on tapping the back key (both device and HMD), whice has two options, one to exit to oculus home and one to exit. How to override this? I don't want to deal with this screen everytime I need to use the back key. Overriding onBackPressed doesn't work. Please reply ASAP. Thanks!

**Comment by liaxim** [comment]
Checking

**Comment by liaxim** [comment]
Quickest fix: revert GVRActivity.java to the bd788ca06c75859cf5ec2664eff40f59afaccb13 commit. We have different configurations that have somewhat conflicting requirements that I will need to deal with differently.

**Comment by sam16222** [comment]
I am directly building examples. Is there a way to revert to the older release?

**Comment by liaxim** [comment]
Are you building the framework yourself or are you using the 3.1 release?

**Comment by sam16222** [comment]
I am using the gradel files given along with the gvrf demos. I just need help overriding the back button so that everytime it is clicked it doesn't go to the "Exit to oculus home" screen

**Comment by liaxim** [comment]
It sounds like you are using the development snapshot we have available from the maven repo. It hasn't been updated in a while. I will look into how to get it up-to-date and include my fix.

Just in case, could you please confirm you are using the gradle files from the GearVRf-Demos master branch? Alternatively you can confirm that you are seeing ``ext.gearvrfVersion='3.1.1-SNAPSHOT'`` in your gradle files. Thanks.

**Comment by liaxim** [comment]
Ok, I updated the snapshots in the maven repo with the latest version plus the backkey fix. Assuming you are using the gradle files from the master branch, you can try again. I tested gvr-immersivepedia with the new version and it works as expected.

It is likely you will have to pass one time the ``--refresh-dependencies`` argument to gradlew if you are building from the command line. Or you can just delete the gradle cache via ``rm -rf ~/.gradle/caches/``.

**Comment by sam16222** [comment]
I am building the immersivepedia application via Android Studio. It shows the onBackPress function doesn't Override an function in superclass (GVRMain). Gradle needn't be updated here right? Let me know what I'm doing wrong.

**Comment by JacobLawtonClaro** [comment]
Go to the GVRMain file, if the path to the file contains "/3.1.1-SNAPSHOT" then the Gradle will need to be updated, because you are using the maven repo.

**Comment by sam16222** [comment]
It does have that. how do I update gradle then?

**Comment by JacobLawtonClaro** [comment]
I am not sure what the good way is but the simple way is to delete the gradle cache.

On windows go to %USER_HOME%.gradle/caches and just delete the cache, then do a clean build of the project and you should have the new SNAPSHOT.

**Comment by sam16222** [comment]
I tried it earlier, didn't work. I'll try again though. the common.gradle file has "ext.gearvrfVersion='3.1.1-SNAPSHOT'" in it. Is this the problem? Or is it supposed to be that.

**Comment by JacobLawtonClaro** [comment]
no that is fine, should work fine by deleting the .gradle file

**Comment by sam16222** [comment]
It's working now. Thank you! For the future, can you tell me what changes should I make to my gradle files in order to keep the latest framework code?

**Comment by JacobLawtonClaro** [comment]
To keep up to data with the latest updates you will need to move away from the maven repo, otherwise you going to have to delete and rebuild every time it's updated.

- Clone this project and have it in the same root as the GVR-demo folder 

- Then build the Framework project, this will put aar files in ..\..\GearVRf-Demos\gearvrf-libs

- GearVRf-Demos\common.gradle, and there are instructions in the comments for swapping to use local dependencies.

-The projects in demo will now build using the .aar files from GearVRf-Demos\gearvrf-libs.

-Then for updates just copy the master update into your local branch.

Better instructions here:
https://resources.samsungdevelopers.com/Gear_VR/020_GearVR_Framework_Project/060_Gear_VRf_Developer_Guide/110_Build_Instructions
https://github.com/Samsung/GearVRf/releases/tag/v3.0.1

**Comment by sam16222** [comment]
Okay thank you for your help.

**Comment by liaxim** [comment]
@sam16222 If you are using the development version of the framework (*-SNAPSHOT) then you will have to delete the gradle cache every once in a while. Most people will find that to be worth it instead of building the framework themselves. The master branch of the GearVRf-Demos is using the development snapshots.

Alternatively you can use the latest stable version in your gradle file. Currently this is 3.1.0. The GearVRf-Demos release-v3.1 branch is using it.

On a somewhat related note, we added a simple template project - https://github.com/gearvrf/GearVRf-Demos/tree/master/template/GVRFApplication. There, amongst other things, you can clearly see the necessary dependencies and adjust your gradle files accordingly.

**Comment by snti** [comment]
Hi @liaxim I'm building with gearvrfVersion='3.2.1-SNAPSHOT' and project.ext.jomlVersion = "1.9.1-SNAPSHOT" and the method onBackPressed is never called.
Any idea?

Regards!

**Comment by liaxim** [comment]
@snti There is a GVRMain.onBackPress() method. This is the full signature: ``public boolean onBackPress()``. Please make sure you override this one and let me know how does it work for you. Just tried with master and it does work for me.

**Comment by snti** [comment]
Thanks @liaxim it worked like a charm!
