### ISSUE TITLE
Use camera passthrough as background "video"

### ISSUE THREAD

**Issue by Nathipha** [Samsung/GearVRf#1069]
First of all: I'm using the the last version of the framework that still works with Eclipse (3.0.1 I think).

What I want to do:
Use the camera passthrough as a full half-screen background "video", similar to how you can set the background color for each eye with:

    scene.getMainCameraRig().getLeftCamera().setBackgroundColor(0.0f, 0.0f, 0.0f, 0.0f);
    scene.getMainCameraRig().getRightCamera().setBackgroundColor(0.0f, 0.0f, 0.0f, 0.0f);

I might go Vuforia's AR route in combination with the Framework at one point but for now I want to do it without - if possible. I set it up like in the "SceneObjectActivity" sample (also 3.0.1, which uses the deprecated "Camera" class - I know that the new versions don't anymore) to test it but that way it's not full half-screen (36f width, 20f height kind of is but it still doesn't look right), plus I'd have to change the z-coordinate every time I add a new scene object to ensure that the "video" stays in the background.

Is it possible to accomplish this without Vuforia and in a way that it's always in the background (without changing the z) and if so, what's the easiest way to do this?

**Comment by liaxim** [comment]
@Nathipha You should use a rendering order of BACKGROUND: ``yourCameraSceneObject.getRenderData().setRenderingOrder(GVRRenderData.GVRRenderingOrder.BACKGROUND)``.

**Comment by Nathipha** [comment]
@liaxim Sorry, completely forgot about the rendering order.
Is there absolutely no way to use it as an actual background like a background color though? The way it's in the sample and I'm also using it at the moment kind of works but if I save all the objects in a scene (scene.getWholeSceneObjects()), clear it, then restore everything to how it was before (via scene.addSceneObject in a "for" loop), breaks it:
The passthrough image gets displayed on a plane that you can actually walk towards and even through, so the whole point of using "scene.getMainCameraRig().addChildObject(cameraObject);" to make it move with the camera breaks.
Sure, I bet removing the passthrough image before saving everything else, then adding it back manually would fix it but still, that and the whole plane situation isn't quite "optimal" for what I have planned.

**Comment by liaxim** [comment]
@Nathipha You could have the passthrough quad placed at a very large negative z in addition to everything else. Since it is supposed to be a background it could help the user with focusing on the right things.

The passthrough quad is a very different thing from the background color. If you had a 360 camera you could show it on a sphere (gvr-360video) but it is not the case so it will look weird.

About your issue with saving and restoring the scene graph.. We have a ``setEnable`` api that will keep your scene objects in the scene graphs but not render them. This way you will avoid removing and adding the scene objects. Since you are using such an old version, I am not sure this API is in there. If not, you can resort to ``GVRRenderData.setRenderMask``. Set it to 0 to disable rendering and ``GVRRenderMaskBit.Left|GVRRenderMaskBit.Right`` to enable.

**Comment by Nathipha** [comment]
@liaxim Even if I had it at -20 or -50, it wouldn't fix my problem because you can walk around in my app (simply moves the camera) and if you move backwards a lot, my scene objects will get further and further away and would eventually get cut off by the passthrough plane - so basically like a render distance setting.  Disabling the depth test helps with this, no matter where the camera and the objects are, but, to be honest, it's not the best solution.
Same problem with having the video on the inside of a sphere but my app is using the S7's back camera, so that won't work in my case anyway.

Oh, that sounds interesting! Is it simply MyGVRSceneObject.setEnable(false)? This is in my version of the framework. I need it to display 1. an image of the controller's button binds and 2. an options menu with a couple of buttons and TextViews (for the actual main menu I have to remove everything anyway). The question is, will this interfere with the passthrough? Currently I stop it and remove the child object, then build it from scratch once I need it again, which hasn't caused it to bug out yet.

**Comment by NolaDonato** [comment]
I don't think it will interfere with the pass through because all it does is prevent the scene object from being rendered by the GPU. It does not change anything about the video or the camera. The object is still in the scene and there is no overhead with enabling or disabling a scene object.

Another component that might help is GVRSwitch. If you attach this component to a scene object it will choose one of the children of that scene object to display and disable all the others. You supply a numeric index to choose which scene object to display.

**Comment by liaxim** [comment]
@Nathipha Why would adding the passthrough quad to the camera rig not work for you exactly?

**Comment by Nathipha** [comment]
@NolaDonato Okay, thanks, I'll try it with setEnable(false) then.
I'll also play around with GVRSwitch and my menus, thanks.

@liaxim 
It does and I did, it just bugged out after readding the object that got saved through "scene.getWholeSceneObjects()". As long as the depth test is disabled and I stop and remove it "manually" before calling "scene.getWholeSceneObjects()" (haven't tested "setEnable(false)" yet), it does what I need it to do (even though it kind of looks weird, not sure what it exactly is) and if there's no way to have it as a fixed background object like the background color, I can keep it the way it is now.

**Comment by liaxim** [comment]
@Nathipha Not sure where we are at with this issue. Planning to close this one soon. Please open a new, more specific one, if you still experience issues. Thanks.
