### ISSUE TITLE
Can i set YUV data into GVRSceneObject？

### ISSUE THREAD

**Issue by codeczx** [Samsung/GearVRf#1134]
Hi, i want to set YUV data which type is ByteBuffer into GVRSceneObject. Is there anyway to achieve it?

**Comment by bohuang3d** [comment]
Hi @codeczx 

YUV as in luminance and red/green values? Do you mean you are loading an image in some non-standard format and want it in GearVRF as a 2d texture?

**Comment by codeczx** [comment]
Yes.

**Comment by bohuang3d** [comment]
https://developer.android.com/reference/android/renderscript/ScriptIntrinsicYuvToRGB.html

Can you use this? Convert to rgb and give it to GVRSceneObject

**Comment by codeczx** [comment]
Do you mean YUV convert to rgb and then convert to bitmap so that i can draw it in canvas? It's too slow.Is there anyway i can use shader which can take advantage of GPU to load YUV data?

**Comment by liaxim** [comment]
Using RenderScript is a high performance option; not saying the only one but it is one. We actually have a sample that does exactly that in our https://github.com/gearvrf/GearVRf-Demos/tree/master/gvr-camera2renderscript sample.

**Comment by senseearth** [comment]
@codeczx 

It sounds like your application is in real time rather than just loading Yuv once. Perhaps streaming video in Yuv and need real time conversion to rgb? Does liaxim's solution work for you?

And yes, as long as you can feed the raw Yuv pixel data into GVRF, then you can author a shader that converts Yuv pixels to RGB via a 3x3 matrix transform:
http://www.equasys.de/colorconversion.html

You may need to be handle gamma conversion correctly too

**Comment by bohuang3d** [comment]
@codeczx

It sounds like your application is in real time rather than just loading Yuv once. Perhaps streaming video in Yuv and need real time conversion to rgb? Does liaxim's solution work for you?

And yes, as long as you can feed the raw Yuv pixel data into GVRF, then you can author a shader that converts Yuv pixels to RGB via a 3x3 matrix transform:
http://www.equasys.de/colorconversion.html

You may need to be handle gamma conversion correctly too

**Comment by hehawjq** [comment]
@bohuang3d 
liaxim's solution is not work for me,how can i feed the raw yuv pixel data with byteBuffer into GVRF?

**Comment by bohuang3d** [comment]
@hehawjq 

I see there is a texture constructor that takes in a Bitmap
GVRBitmapTexture(GVRContext gvrContext, android.graphics.Bitmap bitmap) 
from
http://docs.gearvrf.org/v3.2/Framework/org/gearvrf/GVRBitmapTexture.html

Could you be willing to convert your ByteBuffer to an Android Bitmap each frame, then create GVRBitmapTexture, and assign it to GVRMaterial and use the material on your GVRMesh?

**Comment by liaxim** [comment]
@codeczx It is all hacked up but https://github.com/liaxim/GearVRf-Demos/tree/yuv/VRHackathons/gvr-pokemon shows how to do it for the camera preview frames.

Later I will move some things to the framework and will clean up the sample.

**Comment by hehawjq** [comment]
@bohuang3d  How to use the material on my GVRMesh?

**Comment by hehawjq** [comment]
@liaxim Thanks. It works for me.

**Comment by bohuang3d** [comment]
@hehawjq could be something like:
```

// setup material
        GVRMaterial material = new GVRMaterial(gvrContext);
        material.setMainTexture(myBmpTexture);

        // create a scene object (this constructor creates a rectangular scene
        // object that uses the standard 'unlit' shader)
        GVRCubeSceneObject cubeObject = new GVRCubeSceneObject(gvrContext,
                true, material);
        GVRSphereSceneObject sphereObject = new GVRSphereSceneObject(
                gvrContext, true, material);
```

**Comment by hehawjq** [comment]
@bohuang3d ok,thanks.

**Comment by liaxim** [comment]
Pull request https://github.com/Samsung/GearVRf/pull/1174 merged. Please see the javadoc of the YuvNv21ToRgbShader class on how to use it. Let us know if you have any other questions.
