### ISSUE TITLE
GVRScene Display Problem

### ISSUE THREAD

**Issue by hehawjq** [Samsung/GearVRf#1185]
When running appear permissions box，after click confirm button，the scene become like this.

**Comment by hehawjq** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/3711898/25692427/05eea144-30d5-11e7-9279-ab20430e5898.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/3711898/25692431/0f86e310-30d5-11e7-9d4e-5fce3d62cc08.png)

**Comment by bohuang3d** [comment]
@hehawjq can you try:

Press the phone's menu button to bring up the slide deck view of running applications

swipe/navigate to your application and go back into it

And let me know what happens

**Comment by liaxim** [comment]
@hehawjq Could you please share with us your phone model and Android version? Thanks.

**Comment by hehawjq** [comment]
@liaxim Sumsung S6 and S7，Android6.0.1

**Comment by hehawjq** [comment]
@bohuang3d I try it.it doesn't have display problem.

**Comment by bohuang3d** [comment]
@hehawjq does that mean it's a workaround you can use?

@liaxim it's likely not related to GVRF. I've seen it before with Unity developed application

**Comment by liaxim** [comment]
There has been a similar problem for some time but only apparent on certain phones if you use the GearVR service developer mode. Thus hasn't been a priority. While I can't tell for sure whether the cause is the same, I attempted a fix in https://github.com/Samsung/GearVRf/pull/1186. This does fix the problem I knew about.

@hehawjq Are you using the GearVR service developer mode? If yes, are you ever seeing this problem after docking the phone into the headset?

@hehawjq Can you also let us know the exact phone model obtained via ``adb shell getprop|grep "ro.product.model"``? Is your app itself bringing up the permissions dialog?

@hehawjq I uploaded a new snapshot release for 3.2 that includes my attempted fix. I'd be curious to know what is the effect. You can use the 3.2 snapshot by specifying these dependencies in gradle:
```
ext.gearvrfVersion='3.2.1-SNAPSHOT'
project.ext.jomlVersion = "1.9.1-SNAPSHOT"

dependencies {
    compile 'com.google.code.gson:gson:2.7'
    compile "org.joml:joml-android:${jomlVersion}"
    compile "org.gearvrf:framework:$gearvrfVersion"
    compile "org.gearvrf:backend_daydream:$gearvrfVersion"
    compile "org.gearvrf:backend_oculus:$gearvrfVersion"
    compile 'com.google.vr:sdk-base:1.30.0'
}
```

**Comment by liaxim** [comment]
@hehawjq Do you have anything for us? Thanks.

**Comment by hehawjq** [comment]
@liaxim Sorry reply you so late,I use a new snapshot release for 3.2,It doesn't have this problem.

**Comment by liaxim** [comment]
@hehawjq Great. Then it sounds like we fixed it.
