### ISSUE TITLE
How can i use another PickHandler?

### ISSUE THREAD

**Issue by miraclehwan** [Samsung/GearVRf#1207]
Hi, guys.
1. I used PickHandler(IPickEvents) in GVRMain. 
    I created new Login.class and new PickHandler(IPickEvents) in Login.class.
    But I don't know use PickHandler(IPickEvents) in Login.class

I want flow.
Main.class -> onEnter in  Main.class(IPickEvents) -> setMainscene(login)
-> onEnter in  Login.class(IPickEvents) -> setMainscene(*.class(another class))

This is my source code. I need your kind help. 
Thanks.
https://github.com/miraclehwan/Gear_Test/tree/master/app/src/main/java/com/example/daehwankim/test_work

2. I study GVRf in everyday. but I think guide, infomation and tutorials is not enough.
    if do you know another site, info, guide and tutorials Please Let me know.
github - GearVRf, GearVRf-Demos
site - https://resources.samsungdevelopers.com/Gear_VR/020_GearVR_Framework_Project
         https://forums.oculus.com/developer/

**Comment by liaxim** [comment]
@miraclehwan I an unsure what is the problem that you experience. It seems like the code in the Login class tries to change the background color on the picked scene object. Since you are using GVRTextViewSceneObjects the simplest thing you could do is use the setBackgroundColor method. The picking works fine as far as I can tell.

- if you want to not render a scene object, use setEnable instead of changing the render mask
- I'd recommend not switching scenes; one way to switch between different "views" is to use the GVRSwitch component

We have pretty good tutorial - see https://resources.samsungdevelopers.com/Gear_VR/020_GearVR_Framework_Project/070_GearVRf_Project_Tutorial

If you have particular questions we are always there to help.

**Comment by miraclehwan** [comment]
@liaxim Thanks for your reply.
Sorry,  I can't speak English well...
I can IPickEvents in Main.class
but i don't know onEnter(IPickEvents) in Login.class.


<img src="https://cloud.githubusercontent.com/assets/20110093/26383536/46049768-406e-11e7-84a1-2bc58622cbe5.png">

**Comment by miraclehwan** [comment]
close issues.
