### ISSUE TITLE
GVRAnimation::new GVRAnimation - nested animation crashes api

### ISSUE THREAD

**Issue by nathan-almeida** [Samsung/GearVRf#13]
When trying to nest animations the api crashes.

```java
@Override
public void onStep() {
(...)
     new GVROpacityAnimation(spaceSceneObject, 1f, 0f).setOnFinish(new GVROnFinish() {
            @Override
            public void finished(GVRAnimation animation) {
                new GVROpacityAnimation(shipSceneObject, 2.45f, 1f).setOnFinish(new GVROnFinish() {
                    @Override
                    public void finished(GVRAnimation animation) {
 
                    }
                }).start(mGVRContext.getAnimationEngine());
            }
        }).start(mGVRContext.getAnimationEngine());
    }
(...)
}

```

**Comment by JonShemitz** [comment]
Nathan, I can not reproduce this issue on 1.6.5, whether I launch the nested animation from `onInit()` or `onStep()`. Even when I do something really dumb - launching the nested animation on **every** `onStep()`, so that there are hundred of animations running, stepping on each other - I can not make it crash.

I don't think there's any way to attach a tarball to this issue; could you please mail me the full source of the app that's crashing for you?

**Comment by nathan-almeida** [comment]
Hi Jon,

we were using an older version of gvrf when we reported this issue. We updated it and it's now working just as you said.

I'm closing this issue.
