### ISSUE TITLE
X3D camera position changed in unit tests

### ISSUE THREAD

**Issue by NolaDonato** [Samsung/GearVRf#1322]
The X3D unit tests that import X3D assets no longer work. The camera seems to be farther away in all of them than it used to be. I am not sure if this is because the X3D assets themselves changed or because of modifications to the X3D importer.

The unit tests always center the model and scale it so the bounding box will fit on the screen. The bounding box is apparently much larger now, causing the resulting image to be smaller.

**Comment by mwitchwilliams** [comment]
Yes, the default camera in X3D is at (0, 0, 10) and this was fixed over a month ago.
At one point, the &lt;Viewpoint&gt; node was implemented but had been disabled since some other GearVR changes caused it to stop working.
Many of my latest tests insert **&lt;Viewpoint position='0 0 0'&gt;** just after the &lt;Scene&gt; node.

**Comment by NolaDonato** [comment]
This bug is in the unit tests. They do not take into account the camera position when scaling the output to fit the display. PR #177 in GearVRf-Tests fixes it.
