### ISSUE TITLE
Issues with change #1274 (backend_oculus_camera_rig_reset)

### ISSUE THREAD

**Issue by brian-faber** [Samsung/GearVRf#1389]
https://github.com/Samsung/GearVRf/commit/0a09fc9e5f9fb266fa9ccf4fc62b1ddadc209fd4

We've been noticing odd behavior that is tied to this change. Where sometimes when taking off and putting back on the headset results in the camera rig being rotated 90 or 180 deg (on the Y axis) after prolong use. The issue goes away with rolling back this change.

I sadly haven't had time to investigate further then this.

At the current time I roll back the change in my own build of the libraries but I though I would bring this to your attention.

**Comment by bohuang3d** [comment]
Thanks. Do you know the length of time it takes? 5 minutes? 30 minutes?

**Comment by brian-faber** [comment]
To be honest I am not sure as I haven't had time to fully isolate when and why. It usually happens after using and testing the app out a lot through out the day and when it does happen we were probably running the app for 15m or more. 

The issue did not start happening till after this change was made and it always goes away when this change is reverted and always crops back up when I compile the latest code and forget to take it back out.

**Comment by liaxim** [comment]
@brian-faber Could you please examine your code for any use of the GVRCameraRig.resetXyz() methods? Can you reproduce this problem by following a similar scenario with any of our demo apps? How long do you wait before putting the headset back on? Do you think your activity may be recreated instead of resumed in this case?

The commit just honors the complementary rotation we are supposed to use and which is needed for the resetXyz() methods to actually work.

**Comment by brian-faber** [comment]
Hi,
I don't have answers off hand to your questions. I will investigate and get back to you next week on it.

**Comment by liaxim** [comment]
@brian-faber Do you have anything for us? If not I am planning to close in few days.. I haven't heard anybody else seeing this and we haven't either.

**Comment by brian-faber** [comment]
Hi,
Sorry I never found time to go back and investigate. So for now I will just close the bug.
