### ISSUE TITLE
GVRConsole::writeLine() doesn't print text on screen

### ISSUE THREAD

**Issue by dknaan** [Samsung/GearVRf#150]
GVRConsole::writeLine() used to print text for debugging purpose. Recently it doesn't print anything.
I didn't check yet which commit broke it.

**Comment by chenchao1407** [comment]
No. I think GVRConsole still works. As you may see in the solar system or gvrcollision, the stats messages are actually from a built-in GVRConsole.

Can you just tell me how you use the writeLine()?

**Comment by dknaan** [comment]
In SampleViewManager:
I initialize: console = new GVRConsole(mGVRContext, EyeMode.LEFT_EYE);
And then in onStep() I write: console.writeLine("test");

It used to work for me in the past and this is also what Jon used to write. 

I don't see that writeLine() is called from the ViewManager of solar system or gvrcollision. Is it called from somewhere else?

**Comment by thomasflynn** [comment]
The Stats code uses GVRConsole and calls writeLine().  The solar-system sample uses stats.

**Comment by dknaan** [comment]
When I add stats to simple-sample the data is displayed on the screen, but when I call writeLine() from onStep() with similar code it doesn't.
The main difference I see is that updateStats() is called from GVRViewManager::afterDrawEyes() instead of from onStep().

**Comment by chenchao1407** [comment]
Did you attach the stats to any scene?

**Comment by dknaan** [comment]
The problem is the color of the background. The text is not really printed on the front (it has a depth), so it can be hidden behind the objects and also behind the background...
As a result, a green text is not seen on a white background but it is visible on a black or a gray one.

This should be fixed if we want to continue to use it.

**Comment by lassehe** [comment]
I had issues with GVRConsole too. I suspect it was broken in some point because I remember using it earlier.

If GVRConsole writeLine is called during init the text quickly appears on screen but then disappears. Previous comment about text being behind objects does not seem correct to me, as the console is implemented as a post effect.

Like stated the status console in GVRScene works, though it looks very blocky and ugly. I didn't have much time to look at this now, but I suspect  GVRConsole works there because it is constantly calling setEyeMode which in turn removes and adds post effects to cameras. Is it supposed to be like this? Anyway, at least my own GVRConsole started showing text when I added mConsole.setEyeMode(BOTH_EYES); to my onStep().

**Comment by thomasflynn** [comment]
@Liahim, could you check this out?

**Comment by liaxim** [comment]
Sure

**Comment by liaxim** [comment]
@lassehe Please try this pull request: https://github.com/Samsung/GearVRf/pull/900. Does it do anything for you?

I checked out the GVRConsole and didn't find major problems with it. I did tweak how the final color is produced by the console's fragment shader. Also adjusted the default text size (if you use the current default nothing gets printed out since it is 1). But I didn't see any need to call setEyeMode from onStep.

The blocky text issue - the text kind of looks ok to me. Since it is a debugging facility I don't know how much prettier it should be. In any case, let us know if you have any suggestions.

**Comment by lassehe** [comment]
@liaxim Thanks, this looks like an improvement to me.

You are correct about GVRConsole, no major issues there. My apologies for false alarm. I just found (my) bug causing the GVRConsole to disappear. GVRConsole was created in onInit(), but I was using the constructor **without** GVRScene parameter, so the console disappeared as soon as the splash screen was gone. I hadn't even realized there was two different constructors. That is why adding a setEyeMode() call to onStep was keeping the console visible.

I find the GVRConsole constructor without GVRScene parameter to be slightly deceptive and unnecessary, but at least it looks to be documented well (only for the method with GVRScene parameter though).

I commented looks of GVRConsole mostly because I was remembering it looked significantly better in some point earlier, having a nice sharp normal text. Perhaps I'm remembering wrong. With this patch the text is definitely big enough if not too big (screenshots from gvr-solarsystem):
After:
![solar_new](https://cloud.githubusercontent.com/assets/15195342/19519070/e916a0b0-9612-11e6-94da-31e67afc502a.png)
Before:
![solar_old](https://cloud.githubusercontent.com/assets/15195342/19519071/e917cdf0-9612-11e6-873b-e0c06261243f.png)

**Comment by liaxim** [comment]
@lassehe I will update the demo apps to reflect the different default text size. Will see whether I can do something simple to improve a bit the text appearance.

**Comment by liaxim** [comment]
@dknaan Fyi, white or close to white would mess up the console output since the console used to add the colors (the actual rendered fragment color and the overlay color). I changed the calculation in the shader and the console output is more of an overlay now.

**Comment by liaxim** [comment]
@lassehe Enabled anti aliasing. Text looks much better.

**Comment by liaxim** [comment]
@lassehe The text size should be back to normal in gvr-solarsystem. Thanks for pointing out the problems.
