### ISSUE TITLE
Plugin/Extensions support for GVRf

### ISSUE THREAD

**Issue by lokeshguddu** [Samsung/GearVRf#194]
Hi,

We have been thinking of adding support for plugin/extension for the GVRf. The reason behind this thought was to keep the existing library small and robust and make application specific features as a plugin/extension like remote model loading or SDF font support or anything similar which is specific to an application that is being built on top of the GVRf. 

The major task is to first decide whether it should be a plugin or extension as the distinction between them is still unclear to us. 

So we are starting this issue as to get the opinion of the GVRf community as to what and where to look for and to get a better understanding of the feature to add.

**Comment by thomasflynn** [comment]
We would certainly like to understand better how this would be structured.  We've considered this before.  We can see how gvrf could be used as a plugin.  For example as a plugin to a game engine such that the game engine uses gvrf for head-tracking and stereo and distortion correction.  

As far as plugins/extensions _for_ gvrf, since gvrf is an Android/Java library, we haven't seen much overlap.  If someone wanted to use a library with gvrf, they can just include it in their project.  For example with Vuforia, or JBullet, developers can just include the jar/.so and use the APIs they want.  (we have examples for both vuforia and jbullet).

I think we need to take a look on a case by case basis to see what would be necessary for the best usage with gvrf.

**Comment by thomasflynn** [comment]
i believe the recent libgdx plugin check-ins satisfies this request.
