### ISSUE TITLE
fbx animation

### ISSUE THREAD

**Issue by douglasalipio** [Samsung/GearVRf#224]
Is it possible to work with fbx animation in GVRf Api? Any samples  available?

**Comment by thomasflynn** [comment]
We haven't added support for Assimp's (and therefore fbx's) animations yet.  It's in the plans.  Will likely start work on it later this month.

**Comment by douglasalipio** [comment]
Great!

**Comment by fredduarte** [comment]
Hi, Thomas.

Is there any preview of the FBX support via Assimp on the GearVRf? Also, is there an estimate of when
it will become available on the framework?

**Comment by thomasflynn** [comment]
I'm so sorry.  An internal release here sucked most of us in and took most of our time.  There hasn't been any progress on it in the meantime :(  I don't have a timeline right now.  Hopefully we can get things back on track next week.

**Comment by fredduarte** [comment]
Hello again, Thomas.

For the past couple of weeks, i've been working on a small POC that integrates FBX animation
on the GVR framework.
By no means it is a final result. Its still a WIP branch, but it displays the feature running on the device.
It is based on the tutorial from: [Assimp animation tutorial](http://ogldev.atspace.co.uk/www/tutorial38/tutorial38.html)
I've created some patches for this POC on my fork repository at:
[FBX-animation-branch@repo](https://github.com/fredduarte/GearVRf/commits/fbx-skeletal-animation-POC)

The topmost commit is a video showcasing the animation on a FBX 3D model:
[Test-video](https://github.com/fredduarte/GearVRf/commit/cb71a430fba7fc825ca59070807ad2efa61dd379)

Keep in mind that this has some limitations and i couldn't load some more complex 3D models (with the bones),
and also, i was only able to animate FBX models from version 2013 or newer.
For this last part, i sed the Autodesk FBX converter, which was pretty straightforward.

So,
what do you think?

**Comment by thomasflynn** [comment]
ooo!  cool!  it looks like very good progress in the video.  i'll see if i can take a look at the branch over the weekend.  this is very exciting.

**Comment by thomasflynn** [comment]
ok, did a first pass.  made one comment so far.  otherwise, looks good so far.

**Comment by fredduarte** [comment]
Thomas,

i pushed a couple more patches on the branch which
apply a texture to the already used monster model and centered it on the screen a little more.

Also, i've added one of the immersivepedia's dinosaur model (the T-Rex) to showcase as well.

For now, i'm gonna leave this branch as it is with these examples
and create a new one to start integrating everything correctly with the Framework.

It will take some time to do this, but, i'll keep you updated of major changes i make
so you can review and give suggestions on how to improve.

Hope to have feedback from you again. Tnx.

BR,

**Comment by thomasflynn** [comment]
cool.  can't wait :)

**Comment by danke-sra** [comment]
I looked at your code. It looks like this version has some animation but not including skeletal animation yet. If you have more working code, you may push it and we can see if we can help.

FYI, we are adding a complete version of jassimp (https://github.com/Samsung/GearVRf/pull/309/files), which may help reading bone information from a FBX model. org.gearvrf.jassimp2.AiNode contains AiBone objects. GVRJassimpSceneObject converts AiScene into a tree in GVRSceneObject. However, AiBone is currently not stored in GVRJassimpSceneObject. You may need to add a new class to hold the information.

BTW, we have migrated to Oculus SDK 1.0.0.0. You can get updated build instructions from here: https://github.com/Samsung/GearVRf/releases/tag/2.3

Best regards

**Comment by fredduarte** [comment]
Hi, @danke-sra .

I took a look at your pull-request for the jassimp integration and it seems like it is converting
every Assimp native object (aiScene, aiMesh, aiNode, aiBone, etc) to a java object.

Does this mean that the **assimp_importer.h** header will be removed?

Because, the approach that i'm using for animating the mesh (with the bones) uses the aiScene.
I traverse the the scene nodes starting from the root, both for loading the mesh's aiBones (at the mesh initialization)
and for every animation frame (creating a vector of transform matrices for the shader).
The animation logic is based on native C++ code, and if i use your importer (JAssimp),
it wouldn't be native anymore.

**Comment by danke-sra** [comment]
@fredduarte Thanks for the notice. We actually will keep assimp_importer.{h,cpp} for a while. So no worries about compatibility. When your animation code works (including bones and animations), we may create port that to the new Jassimp importer.

**Comment by danke-sra** [comment]
@fredduarte I see the changes in native code. It would be best if the Java app can start the animation. Then, we can start integrating your solution. =)

**Comment by fredduarte** [comment]
Yes, i'm working on it.
One of the main issues i'm facing also is that i need a reference to the aiScene object
in order to get the root node and the animations arrays (aiAnimation) to perform the animation
on every frame.
Still working on changing that. I'll keep you posted when i push a new branch with the changes.

**Comment by danke-sra** [comment]
AiScene is not a GVRf data structure. Ideally, we want to keep it within the importer area. But before we work that out, you can go ahead to hammer out the animation code and the shader code. Just a heads-up that it may need to be refactored later.

**Comment by danke-sra** [comment]
@fredduarte We added some supporting classes for skeletal animation. Please check it out here: https://github.com/Samsung/GearVRf/pull/318. Can you please see if your work can be based on this infrastructure? We still need to do 1) Support animation imported from assimp. This involves implementing a class such as GVRKeyFrameAnimation, which can provide the transform matrix for a given node at a specific time. 2) Implement a sample to show the animation feature. Please let us know if you can contribute in these areas. Best regards.

**Comment by danke-sra** [comment]
@douglasalipio FYI, some infrastructure is there now. You are welcome to test it out and contribute! Please see https://github.com/Samsung/GearVRf/pull/318

**Comment by fredduarte** [comment]
Hi, @danke-sra . I took a look at the commits on #318 .
I seems that you've already implemented and exposed to Java the Bone, BoneWeights and BoneData classes. These are some of the classes that i use (but, haven't exposed to Java).
It looks good and i'll adapt my solution to use these C++ classes in the future.
For now, i'm currently working on a new version of that branch, but, i'm having some trouble
converting the Matrix4x4 custom class to a glm::mat4 on the animation code.

**Comment by danke-sra** [comment]
I see. I think if you have a Matrix4x4 in Java, the easiest way to pass it to C++ is converting it to float[], though you can pass a java object and access any data and members in JNI as well. You can see https://github.com/Samsung/GearVRf/blob/21f018103e0bc2e727064a047e37e3ceaacfdd6f/GVRf/Framework/jni/objects/components/transform_jni.cpp for reference.

In my version, I've treated the issue of multiple meshes and bone instances when they influence multiple meshes. If you can help review those cases, that will be great! Thanks.

**Comment by fredduarte** [comment]
@danke-sra 
I've uploaded a new branch: https://github.com/fredduarte/GearVRf/commits/animation .
I changed everything to use glm::mat4 matrix instead of the previous custom one, plus,
i created a new shader MeshAnimationShader. Please, take a look.
There is also a sample project to display the animation using the T-Rex from immersivepedia.

I saw that on your SKELETAL branch (which is for review), you are already adding (and exporting)
the bones, boneWeights and vertexBoneData info which i use on my native code.

I need some guidance on how can i integrate part of my solution on your branch, for performing
the animation logic.

**Comment by danke-sra** [comment]
@fredduarte Thanks for the updates. I will test it today and work with you to mainline it.

I've created an "animation-dev" branch and have taken this patch into that. From a quick review, I can see that some assimp data structures (AiScene, AiQuaternion) are used in mesh_animation.cpp file. This is the main thing we need to work on next. As you can see, GVRf has equivalent classes for aiMesh, aiNode, etc. This should apply to animation as well. The reason is that we want to keep the GVRf rendering engine separate from the assimp importer, and allow us to modify and extend GVR classes without being limited by assimp.

I will first test your animation engine, and see how well the algorithm works. After it is working properly, we will try to migrate it to new GVR classes (GVRBone, GVRBoneWeight and GVRVertexBoneData). I will let you know more details about that. Thanks.

**Comment by fredduarte** [comment]
@danke-sra I've pushed another commit on top of the animation branch
which is a small fix. The app was crashing because after some time running,
the garbage collector would delete the assimp importer which contains the aiScene.
This commit fix this problem for now.

**Comment by danke-sra** [comment]
@fredduarte Thanks for the update. I will test with some models and give feedback early next week.

**Comment by danke-sra** [comment]
@fredduarte I have tested your patches and also finished up the Java layer of mesh animation. As you may know, your implementation supports a single mesh, but as I tested, did not fully support multiple meshes (e.g., astro_boy.dae). I have also taken your code BoneData and put in the Java/hybrid version, and used some of your animation code in Java as well (GVRAnimationChannel.java).

I've written a new animation algorithm which handles the global inverse slightly differently, and can support multiple meshes. I've also created some animation classes GVRKeyFrameAnimation which fully uses GVRf animation engine to drive the animation. You can see the sample code in the modified gvrjassimpmodelloader.

What I am thinking is to keep your mesh animation sample and drop the one I created. However, we may prefer moving to the new Java version at some point because we want to support key framed animation in general in Java. I've put all the code in a pull request. Let's try to get it merged. Thanks for your nice contribution.

**Comment by danke-sra** [comment]
@fredduarte We are reviewing the animation code within the team. A general opinion is to avoid using Assimp data structures in animation code. To fit the solution into GVRf architecture, we may need to migrate to the Java version. This does not affect the patches you submitted. I am trying to do so by modifying your MeshAnimationSample (https://github.com/danke-sra/GearVRf/commit/56fa689f518384fd32a6da68e0ef7d1e2dd8f501). Do you think this new API is OK? If so, do you think we can use the new API for other samples (such as immersivepedia)? Best regards.

**Comment by fredduarte** [comment]
@danke-sra I checked the GVRAnimationChannel.java and the other classes. I think its OK. Performance wise looks good.
For immersivepedia sample, we may have to change it a bit. because i tried to use the native code on it and had a few errors when running.
What other parts from my code do you think can be migrated now? I'll use your animation-dev branch as a base for this.
And also, does your current code fully support multiple meshes animation?
BR,

**Comment by danke-sra** [comment]
@fredduarte I've just done refactoring the code. Th performance is better and should support multiple meshes. Please check it out and let us know if you see any problems. Thanks!

**Comment by danke-sra** [comment]
@fredduarte Because we have a new git for samples, I will submit your sample to the sample git instead of the main GVRf git. Thanks. We will finalize the patch soon, and hopefully GVRf will have (skeletal) animation support. Thanks for your work!

**Comment by fredduarte** [comment]
Glad i've helped with this contribution. :)

**Comment by danke-sra** [comment]
This issue is handled by https://github.com/Samsung/GearVRf/issues/224.
