### ISSUE TITLE
The splash screen cuts off on relaunch

### ISSUE THREAD

**Issue by rahul27** [Samsung/GearVRf#283]
Recreation:
1) Open an app.
2) Hit the back button, this will take you to the "Exit to Oculus Home?" Screen.
3) Hit back again.
4) The splash screen appears and then cuts off immediately.

**Comment by liaxim** [comment]
This what I have found thus far (seems to me like an Oculus bug). We draw a frame or two and then the vao id becomes invalid (texture_shader.cpp):
```
glBindVertexArray(mesh->getVAOId(Material::TEXTURE_SHADER_NOLIGHT));
```
fails with 0x0502; the id is there, we do not delete it but sure enough glIsVertexArray returns false. Looks like in this case Oculus runs some stuff too early. Before the vao becoming invalid I can see sched_fifo being applied by Oculus (assuming some additional initialization is going on).

Anyway, in 1.0.0.0 this is a moot point as the whole thing just crashes. Probably because of this:

```
VrApi   : Cannot reset VrApi class loader
```

Will get back to this after 1.0.0.0 is merged.

**Comment by liaxim** [comment]
Oculus apps require android:launchMode="singleTask" in the manifest. Skipping this happened to work mostly in the past but not anymore.

**Comment by liaxim** [comment]
Pull request #301 fixes this issue.
