### ISSUE TITLE
Compile GearVRf on Android Studio 1.5

### ISSUE THREAD

**Issue by xdestiny110** [Samsung/GearVRf#515]
After import GearVRf project into Android Studio, I compile successfully and get gvrf.jar, 
libassimp.so, libgvrf.so, libjnlua.so and libvrapi.so. But when I copy .jar file and .so files into my project and run application, it call error: 

Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK org/mozilla/javascript/tools/resources/Messages.properties
	File1: D:\Project\vr_GearVRApp.git\app\libs\GearVRf.jar
	File2: D:\Project\vr_GearVRApp.git\app\libs\js.jar

Altought I can add packagingOptions in build.gradle to avoid error, but I don't think it is a good way way to solve it. Anyone can help me? Thanks~

**Comment by liaxim** [comment]
Hi,
Not sure how you produced your GearVRf.jar because I get an .aar output that includes the framework jar and the dependencies; supposedly that file should be enough. Would you mind listing the contents of your GearVRf.jar here? What happens if you just remove libs/js.jar from your workspace?

--

For example, this is what I did: created a new AS project. Then I did New->Module->Import from AAR - specified the framework.aar. Updated the dependencies of the initial module to include the newly imported framework module. The project built fine with references to gvrf classes.

**Comment by liaxim** [comment]
Btw, you can always try using one of our release builds: https://github.com/Samsung/GearVRf/releases
