### ISSUE TITLE
Picker not working correctly - see gvr-eyepicking

### ISSUE THREAD

**Issue by liaxim** [Samsung/GearVRf#603]
If GVRMain is in use the picked object keeps flashing in the aforementioned sample. With onStep being executed on the framework thread the picker is not producing the expected results.

**Comment by NolaDonato** [comment]
This is caused by the logic in the application:
1. turn off selection highlighting on all the objects
====== thread switch
2. find the selected object
==== thread switch
3. change the color on the selected object
I am reworking picking to be event based so the application will not have to resort to such logic. It will emit onEnter and onExit events so selection highlighting can be done only when it changes. I have tested with gvr-eyepicking and gvr-pickandmove and the event-based approach eliminates the flickering. Expect picking reform some time next week.

**Comment by NolaDonato** [comment]
PR #204 (pick events) fixes this problem
