### ISSUE TITLE
SpeechRecognizer should be used only from the application's main thread on GVRScript

### ISSUE THREAD

**Issue by DanielNogueiraAndroid** [Samsung/GearVRf#69]
It is possible to run on a class that extends from GVRScript, some code that going to run on main Thread ?
I'm trying to run this code:
 "SpeechRecognizer.createSpeechRecognizer(gvrContext.getContext());"
this is the error:
java.lang.RuntimeException: SpeechRecognizer should be used only from the application's main thread

**Comment by JonShemitz** [comment]
If you pass your GVRActivity to the script’s constructor, you can call Activity methods like runOnUiThread() from your script.

**Comment by DanielNogueiraAndroid** [comment]
Ok it works !!!
You have any idea how to do that if i need to call this code:
"SpeechRecognizer.createSpeechRecognizer(gvrContext.getContext());"
inside a class that extends from GVRSceneObject ?
without pass GVRActivity as parameter (avoiding to have instance of GVRActivity inside GVRSceneObject)  
something like gvrContext.runOnGlThread but for MainThread

**Comment by JonShemitz** [comment]
> without pass GVRActivity as parameter (avoiding to have instance of GVRActivity inside GVRSceneObject)  like gvrContext.runOnGlThread but for MainThread

We're having a slow-motion internal discussion about exposing the `GVRActivity` _via_ `GVRContext`. One of the changes I made very early on was changing `GVRContext.getContext()` to return the `ApplicationContext`, not the `Activity`. This was robotic, Android 101 thinking on my part: You don't hold onto an `Activity` because that can be a huge memory leak. But GVRF has turned out to be very single-`Activity`, and we'll probably

1. Let `GVRContext.getContext()` return the `GVRActivity`, as a `Context`.
2. Add a new `GVRActivity GVRContext.getActivity()` that will give you access to all the `Activity` methods.

**Comment by DanielNogueiraAndroid** [comment]
Great !!!

**Comment by JonShemitz** [comment]
Pull request https://github.com/Samsung/GearVRf/pull/80
