### ISSUE TITLE
A scene object cannot be added to a scene after clear()

### ISSUE THREAD

**Issue by danke-sra** [Samsung/GearVRf#692]
UnsupportedOperationException is raised. The error message is "GVRSceneObject cannot have multiple parents".

**Comment by NolaDonato** [comment]
Yes, this is because a scene object cannot have two parents. We were not checking for this before and it can cause a log of problems internally. For example, if the object has two parents, what is it’s model matrix? Which parent do you use to calculate it?

Now it will throw an exception if you try to add a scene object to another hierarchy if it is already in one. The simple fix is to remove it from the existing hierarchy and then add it to the new one:

sceneObject.getParent().removeChildObject(sceneObject)

will remove it from the hierarchy.



-Nola

**Comment by danke-sra** [comment]
Thanks. So it's should be easy to fix. I will try setting the parents to null when the scene is cleared.

**Comment by liaxim** [comment]
@danke-sra Can we close then?

**Comment by danke-sra** [comment]
GVRScene.clear() needs to be fixed to set the parents of the removed scene objects to null. Should be easy. I will submit a change tomorrow.

**Comment by NolaDonato** [comment]
This is fixed in the scriptbehavior pull request #668. Perhaps you can test it.

**Comment by danke-sra** [comment]
FYI, I tested it but this is still not fixed by https://github.com/Samsung/GearVRf/pull/699.
