### ISSUE TITLE
Custom shader won't render a mesh if any of the texture is missing

### ISSUE THREAD

**Issue by deepakrawat22** [Samsung/GearVRf#796]
In case if there are several textures like specular, diffues, bump etc. If only one is missing due to unsupported file format or any other reason, custom shader will not render due to the condition.

```
        std::lock_guard<std::mutex> lock(textureVariablesLock_);
        for (auto it = textureVariables_.begin(); it != textureVariables_.end(); ++it) {
            Texture* texture = material->getTextureNoError(it->key);
            if (texture == NULL) {
            	LOGE(" texture is null for %s", render_data->owner_object()->name().c_str());
            	return;
            }
```

**Comment by NolaDonato** [comment]
I have a suggestion for missing textures. GVRAssetLoader.TextureRequest handles the loading of textures for imported assets. The “failed” function is called if the texture load fails and it goes on to generate the “onTextureError” event. You might be able to preload a 32x32 white texture and then call the “loaded” function with that texture as an argument. I am not 100% sure that will work because I don’t know if you can call “loaded” after “failed”. But we can get this to work somehow, we can always ensure there will be some kind of texture on loaded assets.

Of course, this will do nothing for scene objects created programmatically…

-Nola

**Comment by liaxim** [comment]
@deepakrawat22 Please remove those checks and let us know what happens. The error shader should let us see something.

**Comment by deepakrawat22** [comment]
With the latest code, the model is rendered if some texture is missing.

**Comment by NolaDonato** [comment]
This was fixed by the embedded textures patch.
