### ISSUE TITLE
Scissoring in Grvrf

### ISSUE THREAD

**Issue by ananthaks** [Samsung/GearVRf#798]
In OpenGL we can control the region of drawing using glscissor. Can we do something similar here by restricting the rendering of a GVRSceneObject to only a particular region (given cuboid) ? This restriction should be applied only to the specified SceneObject.

I wanted to implement a scrollable list of item like ListView in Android. I implemented this by adding GVRSceneObjects to a parent object and adjusting the x, y position of each item. However I want to show only a part of the list to the user. The Other items must not be visible. Currently I am manually checking if the position of each item exceeds that of the list boundary and making it invisible/visible. However there causes and abrupt change.

I think a better solution should be there for this problem.

**Comment by NolaDonato** [comment]
We don’t expose the scissor but you can do the same thing with depth testing and rendering order.


1.       Background objects: rendering order N, depth test on

2.       Clip object: rendering order N+1, depth test on, alpha blend on, alpha = 0 (completely transparent)

3.       List view object: rendering order N+2, depth test on

The clip object should be a plane with a hole in it where you want to see the list view. It should be completely transparent. It will be rendered after the background so it will update the depth buffer but the background will show thru completely. This clip object should have a Z value putting it IN FRONT of the list view object even though it will be rendered before that object (because you set the rendering order to a smaller value).

GearVRF will render objects in ascending rendering order so the background will be rendered first. The clip object will update the depth buffer so that anything drawn BEHIND it will show thru the hole but will be obscured by the transparent clip area (the depth buffer will do the clipping for us).

**Comment by ananthaks** [comment]
@NolaDonato 
Thanks a lot. It worked like you said with some modifications.
