### ISSUE TITLE
Android emulator

### ISSUE THREAD

**Issue by maragh** [Samsung/GearVRf#802]
Just curious, can i use an emulator during development for testing?

**Comment by liaxim** [comment]
To my knowledge - not possible.

**Comment by maragh** [comment]
Ok, thanks.

**Comment by thomasflynn** [comment]
It would likely be somewhat painful to do.  Oculus only provides 32bit arm libraries.  Which means you would need to set up an arm emulator (rather than an x86 one).  In that emulator, we would detect the oculus service is not on the system and fall back to daydream.  However, in our experience, running an arm emulator is horrifically slow, especially for anything GL related.  It's best to stick with a physical phone for development.
