### ISSUE TITLE
.fbx file support

### ISSUE THREAD

**Issue by thomasflynn** [Samsung/GearVRf#85]
Assimp 3.1 (which we use) has support for the .fbx format.  However, that code requires rtti support.  The oculus sdk requires compiling with -fno-rtti.  We cannot link them in the same application :(.  Need to find a work-around.

**Comment by deepakrawat22** [comment]
Compiled Assimp with RTTI flag on and still have issue in loading fbx file. Without passing hint parameter as "fbx" in Assimp::Importer.ReadFileFromMemory() assimp will simple return NULL. After hint as "fbx" there is segmentation fault in assimp.

07-01 18:17:49.940: A/libc(24979): Fatal signal 7 (SIGBUS), code 1, fault addr 0xa0d1b456 in tid 25049 (GLThread 14839)

Currently I tried loading fbx model from asset director of Android so assimp will read from memory. Can try loading fbx from SD card.

**Comment by jason2kim** [comment]
Deepak, at SIGBUS, do you have any stack information that shows the crashed line number, coming from a native tool? In case you want to peek into, the crashed source line would give some clue.

**Comment by jason2kim** [comment]
Chao, are you using addr2line tool something simple one that Deepak can use for native codes?

**Comment by chenchao1407** [comment]
Please take a look at this link to see how to use arm-eabi-addr2line
http://stackoverflow.com/questions/2314273/get-function-names-from-call-stack

And please see the answer with 15 "useful".

In our case, /path/to/lib/with/symbols.so refers to /GVRf/Framework/obj/local/armeabi-v7a/libgvrf.so

**Comment by chenchao1407** [comment]
And if you can't find arm-eabi-addr2line in your ndk folder. I can send you my own copy.

Thanks

**Comment by thomasflynn** [comment]
if you look at the NDK programmer's guide located in your android-ndk folder (android-ndk-r10d/docs/Programmers_Guide/html/md_3__key__topics__debugging_debugging.html), you'll see there is an ndk-stack command that can help with this.  this'll essentially do the addr2line on the stacktrace given what you see in logcat.

**Comment by deepakrawat22** [comment]
Assimp is loading FBX file even with the old compiled assimp.so library. We just need to pass the fbx string as hint parameter in the Assimp::Importer.ReadFileFromMemory() API. Currently NULL is passed and Assimp try to guess the format and fails so get NULL mesh and that's why segmentation fault.

With the above change, still there is a minor problem. All the fbx file I have are having quad faces (Or FBX only support quad face). In GearVRf, the code to load the faces from assimp scene ignores quad faces:

  for (int i = 0; i < ai_mesh->mNumFaces; ++i) {
        if (ai_mesh->mFaces[i].mNumIndices == 3) {
            triangles.push_back(ai_mesh->mFaces[i].mIndices[0]);
            triangles.push_back(ai_mesh->mFaces[i].mIndices[1]);
            triangles.push_back(ai_mesh->mFaces[i].mIndices[2]);
        }

I observed that any wavefront file with quad faces is also not getting displayed. So we need to add quad faces support also.

Meanwhile to support fbx or any mesh file we can add the hint string based on file extension to the Assimp::Importer.ReadFileFromMemory() API.

**Comment by phi-lira** [comment]
FBX supports both quad and triangle faces. Most of the models you'll find will be quads because it's easier for 3D artists to work that way.

There's a triangulate method exposed in the FBXSDK that will convert from quad face mesh to triangles but I don't know if there's something similar on Assimp. If not, it's really easy to make a c++ tool to triangulate fbx models offline. The problem is that GearVRf users would need to be aware of that and preprocess their models using this tool.

**Comment by deepakrawat22** [comment]
Pull Request #154 will conclude this enhancement request.
