### ISSUE TITLE
remove getOwnerObject from samples.

### ISSUE THREAD

**Issue by thomasflynn** [Samsung/GearVRf#97]
verify we can get rid of getOwnerObject from our samples.  and see we can possibly deprecate that api all together.

**Comment by deepakrawat22** [comment]
After some analysis I found that get/setOwnerObject is used extensively in the Framework. Even in JNI code owner object is used by transform, render data. Owner object is used to main transformation hierarchies in scene objects.

So I think the objective of this enhancement will only be limited to removing getOwnerObject from Application usage?

In case of GVREyePointeeHolder, there is already a new API provided List<GVRPickedObject> findObjects(..), which do not return GVREyePointeeHolder so owner object can be avoided in this case.

**Comment by jason2kim** [comment]
1) In Solar System demo app, … not able to get rid of this usage
=> Removing this is important for the app developers. Can you consider channg in JNI level if needed?

2) Once done, we need to make getOwnerObject(), if still alive, visible only to the framework package, not to the applications as public.

3) otherwise this change is only a second best solution^^

**Comment by jason2kim** [comment]
If too much for changing the JNI side, a Java side trick would be overloading GVRSceneObject.addChildObject() with GVRComponent or GVRCameraRig. But, it would be not so consistent as you know.
